title: Tasos Sangiotis
url: https://tsangiotis.com
description: Inputs & Outputs
author: Tasos Sangiotis

repository: tsangiotis/tsangiotis.github.io

theme: null

permalink: /:title/
highlighter: rouge

excerpt_separator: <!--more-->

collections:
  books:
    title: Books

social:
  twitter: tsangiotis

avatar_img: me.png

photo:
  title: Travolta Athens
  img: https://world.hey.com/tasos/7e8ccb87/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCTXB6MENnPSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fad6df53fd7ee6491015304ceb49a05d73f8cd89/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDam9MWm05eWJXRjBTU0lJU2xCSEJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFLQUIya0NBQVU2REhGMVlXeHBkSGxwU3pvTGJHOWhaR1Z5ZXdZNkNYQmhaMlV3T2cxamIyRnNaWE5qWlZRPSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--afd0597065e95e7fda232779605f74232acbb77e/IMG_0852.JPG
  url: https://world.hey.com/tasos/travolta-athens-mialigoura-7e8ccb87

feed:
  posts_limit: 200

exclude: ["README.md", "Gemfile.lock", "Gemfile", "Rakefile"]

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
