title: Tasos Sangiotis
url: https://tsangiotis.github.io
baseurl:
description: Inputs & Outputs
author: Tasos Sangiotis

repository: tsangiotis/tsangiotis.github.io

theme: null

permalink: :title/
highlighter: rouge

excerpt_separator: <!--more-->

social:
  twitter: tsangiotis

avatar_img: me.png

image:
  title: Window girl
  img: https://imagedelivery.net/mdSbb1GKWP_xXxxsYl5evQ/e1371af3-916c-4db7-0f85-26bddbd01f00/optimised
  url: https://www.instagram.com/p/CZos_TFsNxg/?utm_medium=copy_link

collections:
  books:
    title: Books
    output: true

feed:
  posts_limit: 200

exclude: ["README.md", "Gemfile.lock", "Gemfile", "Rakefile", "vendor"]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache

