title: Tasos Sangiotis
url: https://tsangiotis.com
description: Inputs & Outputs
author: Tasos Sangiotis

repository: tsangiotis/tsangiotis.github.io

permalink: /:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

twitter_username: tsangiotis

ganalytics: UA-72716429-1

gems:
  - jekyll-sitemap
  - jekyll-seo-tag