title: Tasos Sangiotis
url: https://tsangiotis.com
baseurl:
description: Inputs & Outputs
author: Tasos Sangiotis

repository: tsangiotis/tsangiotis.github.io

theme: null

permalink: :title/
highlighter: rouge

excerpt_separator: <!--more-->

social:
  twitter: tsangiotis

avatar_img: me.png

compress_images:
  images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"

image:
  title: don’t look as i just hide now in this creepy old and inefficient 5 person bar
  img: /images/andros/IMG_0676.jpeg
  url: https://www.instagram.com/p/CZos_TFsNxg/?utm_medium=copy_link

collections:
  books:
    title: Books

feed:
  posts_limit: 200

exclude: ["README.md", "Gemfile.lock", "Gemfile", "Rakefile"]

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-compress-images
  - jekyll-include-cache
