name: tasos sangiotis
url: https://tsangiotis.com
description: inputs and outputs

repository: tsangiotis/tsangiotis.github.io.

permalink: /:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

twitter_username: tsangiotis

ganalytics: UA-72716429-1

jekyll-sitemap

gems:
  - jekyll-sitemap