title: Tasos Sangiotis
url: https://tsangiotis.com
description: Inputs & Outputs
author: Tasos Sangiotis

repository: tsangiotis/tsangiotis.github.io

permalink: /:title/
highlighter : rouge

paginate: 6
paginate_path: "/page/:num/"

excerpt_separator: <!--more-->

collections:
  - links

social:
    twitter: tsangiotis

avatar_img: me.png

feed:
    path: index.xml

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
