title: Tasos Sangiotis
url: https://tsangiotis.com
baseurl:
description: Inputs & Outputs
author: Tasos Sangiotis

repository: tsangiotis/tsangiotis.github.io

theme: null

permalink: :title/
highlighter: rouge

excerpt_separator: <!--more-->

social:
  twitter: tsangiotis

avatar_img: me.png

image:
  title: Peccati di gola @ mialigoura
  img: /images/peccati-di-gola-mialigoura/IMG_0087.jpg
  url: /peccati-di-gola-mialigoura

collections:
  books:
    title: Books

feed:
  posts_limit: 200

exclude: ["README.md", "Gemfile.lock", "Gemfile", "Rakefile"]

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
