title: Old posts by Tasos Sangiotis
url: https://tsangiotis.com
baseurl: /blog
description: Inputs & Outputs
author: Tasos Sangiotis

repository: tsangiotis/blog

theme: null

permalink: :title/
highlighter: rouge

excerpt_separator: <!--more-->

social:
  twitter: tsangiotis

avatar_img: me.png

feed:
  posts_limit: 200

exclude: ["README.md", "Gemfile.lock", "Gemfile", "Rakefile"]

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
