name: tasos sangiotis
url: https://tsangiotis.com
subtitle: inputs and outputs
author: Tasos Sangiotis

repository: tsangiotis/tsangiotis.github.io.

permalink: /:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

twitter_username: tsangiotis

ganalytics: UA-72716429-1

gems:
  - jekyll-sitemap
  - jekyll-seo-tag