title: Tasos Sangiotis
url: https://tsangiotis.com
description: Inputs & Outputs
author: Tasos Sangiotis

repository: tsangiotis/tsangiotis.github.io

permalink: /:title/
highlighter : rouge

paginate: 6
paginate_path: "/page/:num/"

excerpt_separator: <!--more--> 

feed:
    path: index.xml

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

twitter_username: tsangiotis

ganalytics: UA-72716429-1

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
